// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZD8Ddc5QDir2rFRNiF5cm3jsLz52MAPo',
    appId: '1:137917064655:web:980564cbb182e5d2e11eba',
    messagingSenderId: '137917064655',
    projectId: 'nah-id-revise',
    authDomain: 'nah-id-revise.firebaseapp.com',
    storageBucket: 'nah-id-revise.firebasestorage.app',
    measurementId: 'G-6EXJ7SZSLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdxkIH354TgsqWpljQ6MepKvMB7T5Ni1g',
    appId: '1:137917064655:android:a8642c39cf4f458de11eba',
    messagingSenderId: '137917064655',
    projectId: 'nah-id-revise',
    storageBucket: 'nah-id-revise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfkknJZm1VFMZFwfG6nHTO3pvBcFBB4qM',
    appId: '1:137917064655:ios:88731173f5895e11e11eba',
    messagingSenderId: '137917064655',
    projectId: 'nah-id-revise',
    storageBucket: 'nah-id-revise.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfkknJZm1VFMZFwfG6nHTO3pvBcFBB4qM',
    appId: '1:137917064655:ios:88731173f5895e11e11eba',
    messagingSenderId: '137917064655',
    projectId: 'nah-id-revise',
    storageBucket: 'nah-id-revise.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZD8Ddc5QDir2rFRNiF5cm3jsLz52MAPo',
    appId: '1:137917064655:web:6379c9fec500ac90e11eba',
    messagingSenderId: '137917064655',
    projectId: 'nah-id-revise',
    authDomain: 'nah-id-revise.firebaseapp.com',
    storageBucket: 'nah-id-revise.firebasestorage.app',
    measurementId: 'G-L7RJWGB9PB',
  );
}
